# Generated by Django 6.0.4 on 2026-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyApp', '0002_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('UNDER_OFFER', 'Under Offer'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20),
        ),
    ]
