# Generated by Django 6.0.4 on 2026-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyApp', '0006_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycategory',
            name='name',
            field=models.CharField(default='Categories', max_length=100),
        ),
    ]
