# Generated by Django 6.0.4 on 2026-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyApp', '0007_alter_propertycategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
