# Generated by Django 6.0.4 on 2026-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyApp', '0008_alter_property_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_plan_approval',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='c_of_o',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20, verbose_name='C of O'),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_status',
            field=models.CharField(choices=[('BARE_LAND', 'Bare Land / Unimproved'), ('OFF_PLAN', 'Off-Plan'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='deed_of_assignment',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='governors_consent',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20, verbose_name="Governor's Consent"),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size',
            field=models.CharField(blank=True, help_text="e.g., '600 sqm' or '2 Plots'", max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registered_survey',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='sq_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_size',
            field=models.CharField(blank=True, help_text='Built-up area (leave blank for land)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Write a comprehensive, long detailed note about the property features, neighborhood, topography, etc.'),
        ),
    ]
