# Generated by Django 6.0.4 on 2026-06-06 18:42

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models

from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('propertyApp', '0009_property_building_plan_approval_property_c_of_o_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        
        migrations.AlterField(
            model_name='property',
            name='building_plan_approval',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='Not_Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='c_of_o',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='Not_Available', max_length=20, verbose_name='C of O'),
        ),
        migrations.AlterField(
            model_name='property',
            name='construction_status',
            field=models.CharField(choices=[('BARE_LAND', 'Bare Land / Unimproved'), ('OFF_PLAN', 'Off-Plan'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('COMPLETED', 'Completed')], default='Completed', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='deed_of_assignment',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='Not_Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='governors_consent',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='Not_Available', max_length=20, verbose_name="Governor's Consent"),
        ),
        migrations.AlterField(
            model_name='property',
            name='registered_survey',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='Not_Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('UNDER_OFFER', 'Under Offer'), ('SOLD', 'Sold')], default='Available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'category', 'price'], name='propertyApp_status_ef22d7_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category', 'price'], name='propertyApp_categor_2e97bf_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['property_address'], name='property_address_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='property_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
